#! /bin/bash

##
## Oracle key derivation function
##
function _derive_key {
    local pass=$1
    salt=051399429372e8ad
    key="`echo -n $pass | xxd -p`$salt"
    for i in {1..42}
    do
	key=$(echo -n $key | xxd -revert -plain | md5sum)
    done
    echo $(echo -n $key | cut -d ' ' -f 1)
}

function _secret_key {
    local key=$1
    echo $(echo -n $key \
	       | xxd -plain -revert \
	       | cut -b1-8 \
	       | tr --delete [:space:] \
	       | xxd -plain)
}

function _iv {
    local iv=$1
    echo $(echo -n $key \
	       | xxd -revert -plain \
	       | cut -b9- \
	       | tr --delete [:space:] \
	       | xxd -plain)
}

##
## Decrypt des-cbc encrypted password
##
function _decrypt {
    local secret_key=$1
    local iv=$2
    local cypher_text=$3
    echo $(echo -n $cypher_text \
	       | openssl enc -d -des-cbc -a -A -K $secret_key -iv $iv)
}

##
## Encrypt password with des-cbc
##
function _encrypt {
    local secret_key=$1
    local iv=$2
    local plain_text=$3
    echo $(echo -n $plain_text \
	       | openssl enc -e -des-cbc -a -A -K $secret_key -iv $iv)
}

##
## Tests
##
if [ ! -z $unittest ]
then
    echo "TestKeyIsDerived"
    expect_key=8038ddc176ac45736352a143e0ce5fb4
    key=$(_derive_key pass)
    test $key = $expect_key \
	&& echo -e "\033[32mpassed ($key = $expect_key)\033[0m" \
	    || echo -e "\033[31mfailed, expected key = $expect_key but got $key\033[0m"

    echo "TestSecretKeyIsDerived"
    expect_secret_key=8038ddc176ac4573
    secret_key=$(_secret_key $key)
    test $secret_key = $expect_secret_key \
	 && echo -e "\033[32mpassed ($secret_key = $expect_secret_key)\033[0m" \
	     || echo -e "\033[31mfailed, expected secret_key = $expect_secret_key but got $secret_key\033[0m"

    echo "TestIVIsDerived"
    expect_iv=6352a143e0ce5fb4
    iv=$(_iv $key)
    test $iv = $expect_iv \
	 && echo -e "\033[32mpassed ($iv = $expect_iv)\033[0m" \
	     || echo -e "\033[31mfailed, expected iv = $expect_iv but got $iv\033[0m"

    echo "TestDecrypt"
    expect_plain_text=myPass2
    plain_text=$(_decrypt $secret_key $iv mr1Ve8X3UXQ=)
    test $plain_text = $expect_plain_text \
	 && echo -e "\033[32mpassed ($plain_text = $expect_plain_text)\033[0m" \
	     || echo -e "\033[31mfailed, expected plain_text = $expect_plain_text but got $plain_text\033[0m"

    echo "TestEncrypt"
    expect_cypher_text=mr1Ve8X3UXQ=
    cypher_text=$(_encrypt $secret_key $iv myPass2)
    test $cypher_text = $expect_cypher_text \
	 && echo -e "\033[32mpassed ($cypher_text = $expect_cypher_text)\033[0m" \
	     || echo -e "\033[31mfailed, expected cypher_text = $expect_cypher_text but got $cypher_text\033[0m"

    exit 0
fi

function _usage {
    echo "usage: `basename $0` [encrypt|decrypt] TEXT KEY"
}


##
## Main
##
if [ -z $1 ] || [ -z $2 ]
then
    _usage
    exit 1
fi

if [ $1 = "encrypt" ] && [ ! -z $3 ]
then
    MODE=encrypt
    shift
elif [ $1 = "decrypt" ] && [ ! -z $3 ]
then
    MODE=decrypt
    shift
fi
text=$1
pass=$2
key=$(_derive_key $pass)

case $MODE in
    "encrypt")
	cypher_text=$(_encrypt $(_secret_key $key) $(_iv $key) $text)
	if [ ! -z $cypher_text ]
	then
	    echo $cypher_text
	fi
	;;
    "decrypt")
	plain_text=$(_decrypt $(_secret_key $key) $(_iv $key) $text)
	if [ ! -z $plain_text ]
	then
	    echo $plain_text
	fi
	;;
    *)
	_usage
	;;
esac
